services:
  - docker
  
script:
- git clone https://github.com/cloudflare/flan.git
- cat ./flan/shared/ips.txt
- cp ips.txt flan/shared/ips.txt
- cat ./flan/shared/ips.txt
- ls
- cd flan
- docker --version
- make build
- DATE=$(date +"%Y.%m.%d-%H.%M")
- sudo mkdir -p /shared/xml_files/$DATE
- ls -l /shared/xml_files
- sudo make start
- make html
- cd shared/reports
- ls
- cat *.html
#- (make start >> start.out ; touch end.end) &
#- cp ../waitEnd.sh waitEnd.sh
#- chmod +x waitEnd.sh
#- ./waitEnd.sh
#- tail -n 500 start.out
