#!/bin/bash

open -a Docker
rm -r flan/
git clone https://github.com/cloudflare/flan.git
cat ./flan/shared/ips.txt
cp ips.txt flan/shared/ips.txt
cat ./flan/shared/ips.txt
cd flan
docker --version
make build
make html
cd shared/reports
ls
cat $(ls)
