#!/bin/bash

open -a Docker
rm -r flan/
git clone https://github.com/cloudflare/flan.git
az network dns record-set list -z applitools.com -g ApplitoolsManagement --subscription "Applitools Eyes" > urls.json
./print_CNAME_or_A_entries.sh urls.json > ips.txt
cat ./flan/shared/ips.txt
cp ips.txt flan/shared/ips.txt
cat ./flan/shared/ips.txt
cd flan
docker --version
make build
make start
make html
cd shared/reports
ls
