name: CI

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
      - run: |
          chmod +x runFlan
          chmod +x print_CNAME_or_A_entries.sh
          chmod +x remove_black_list.sh
          sudo ./runFlan
#       - uses: actions/checkout@v2
#       - name: Use Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '15.x'
#       - run: git clone https://github.com/cloudflare/flan.git
#       - run: cat ./flan/shared/ips.txt
#       - run: cp ips.txt flan/shared/ips.txt
#       - run: cat ./flan/shared/ips.txt
#       - run: ls
#       - run: cd flan
#       - run: docker --version
#       - run: make build
#       - run: make start
#       - run: make html
#       - run: cd shared/reports
#       - run: ls
#       - run: cat *.html
