# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo ${{ secrets.PREFLIGHT_CLIENT_ID }}
      - run: |
          npm i -g preflight-cli      
          preflight run_test --clientId=${{ secrets.PREFLIGHT_CLIENT_ID }} --clientSecret=${{ secrets.PREFLIGHT_SECRET }} --testId="Pi535A2uHR8G" --environmentId="jlmjNF4suDdm" --browsers="win-chrome" --sizes="1440x900"
#       - uses: actions/checkout@v2
#       - name: Use Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '15.x'
#       - run: git clone https://github.com/cloudflare/flan.git
#       - run: cat ./flan/shared/ips.txt
#       - run: cp ips.txt flan/shared/ips.txt
#       - run: cat ./flan/shared/ips.txt
#       - run: ls
#       - run: cd flan
#       - run: docker --version
#       - run: make build
#       - run: make start
#       - run: make html
#       - run: cd shared/reports
#       - run: ls
#       - run: cat *.html
